[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class term"
class = "term"
lazy = true
size = "75% 45%"

#[scratchpads.ranger]
#command = "terminator --class scratchpad -e ranger"
#margin = 50

#[scratchpads.numbat]
#command = "terminator --class scratchpad -e numbat"
#margin = 50

#[scratchpads.musikcube]
#command = "terminator --class scratchpad -e musikcube"
#margin = 50
[scratchpads.spotify_scratch]
animation     = "fromBottom"
command       = "flatpak run --branch=stable --arch=x86_64 --command=spotify --file-forwarding com.spotify.Client"
class         = "Spotify"
initialClass  = "Spotify"
app_id        = "com.spotify.Client"
lazy          = true
size          = "75% 45%"
unfocus       = "hide"
#[scratchpads.pavucontrol]
#command = "pavucontrol"
#margin = 50
#unfocus = "hide"
#animation = "fromTop"
