#!/bin/zsh

# Source zsh_config.sh from the same directory
source ~/.zshrc

# Ensure $THM is set
if [ -z "$THM" ]; then
    echo "Error: THM variable is not set."
    exit 1
fi

# Run nmap command
nmap -sC -sV -T4 "$THM"
